In [1]:
import numpy as np

Найдите сумму и произведение матриц  A=(13−20)  и  B=(40−15).

In [2]:
a = np.array ([[1,-2],[3,0]])
b = np.array ([[4,-1],[0,5]])

In [3]:
print(f'Матрица ab\n{np.dot(a, b)}')
print(f'Матрица С = A + B\n{a + b}')

Матрица ab
[[  4 -11]
 [ 12  -3]]
Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию  3A−2B+4C  для матриц  A=(137−6) ,  B=(025−1) ,  C=(21−41).

In [5]:
A = np.array ([[1,7],[3,-6]])
B = np.array ([[0,5],[2,-1]])
C = np.array ([[2,-4],[1,1]])
k = 3
m = -2
n = 4

In [8]:
print(f'Матрица D  \n{k*A+m*B+n*C}')

Матрица D  
[[ 11  -5]
 [  9 -12]]


Дана матрица  A=⎛⎝⎜4521−23⎞⎠⎟ . Вычислите  AAT  и  ATA .

In [9]:
A = np.array ([[4,1],[5,-2],[2,3]])
B = A.T

In [10]:
print(f'Матрица AAt  \n{np.dot(A,B)}')

Матрица AAt  
[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [11]:
print(f'Матрица AtA  \n{np.dot(B,A)}')

Матрица AtA  
[[45  0]
 [ 0 14]]


2 часть

Вычислить определитель

In [8]:
A = np.array ([[4,2,3],[0,5,1],[0,0,9]])

In [10]:
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Определитель:
180


In [11]:
A = np.array ([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Определитель:
-0


In [14]:
A = np.array ([[1,2,3],[1,1,1],[2,3,4]])

In [15]:
r = np.linalg.matrix_rank(A)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [16]:
A = np.array ([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])

In [17]:
r = np.linalg.matrix_rank(A)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
